name: Entrypoint2

on:
  workflow_dispatch:
    inputs:
      build:
        type: boolean
        default: false
        description: "Run build"
      deploy:
        type: boolean
        default: false
        description: "Run deploy"
  push:
    branches-ignore:
      - release-please**
    tags:
      - v**

jobs:
  build:
    name: Build
    if: ${{ inputs.build == true }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: EBCONT-Conference/devopsdays.demo.reusable-workflow.build.docker/.github/workflows/entrypoint.yml@v1
    secrets: inherit

#  deployment:
#    name: Deployment
#    uses: ebcont/ebcont.it-support.reusable-workflow.deployment.helm/.github/workflows/entrypoint.yml@v6
#    if: ${{ inputs.deploy == 'true' && always() && !failure() }}
#    needs: [ build ]
#    secrets: inherit
